### ISSUE TITLE
Webservice Configs and Workflow Configs show up in list with UNKNOWN creator

### ISSUE THREAD

**Issue by kaiec** [DM2E/dm2e-gui#1]
When playing around with OmNom, creating a workflow and running it (it FAILED so far all the time), in the config list are webservice configs AND workflow configs (but older one, not created by me) that have UNKNOWN as creator.

**Comment by kba** [comment]
Who should be the creator of a webservice config created by a workflow? Should probably use `prov:wasGeneratedBy` in general for webservice configs instead of dc:creator.

**Comment by kaiec** [comment]
Yes, makes sense. What if a service is invoked outside a workflow? Then the creator still makes sense. We could keep it and fill it with either the workflow (it is an agent anyway, right?) or the user associated with the workflow, i.e., who runs it.

**Comment by kba** [comment]
The config list now shows either a link to the user or the job that created the config.
