### ISSUE TITLE
What is the use of the edit button in the file manager (for xml files or xslts that do not come from mint)?

### ISSUE THREAD

**Issue by edroege** [DM2E/dm2e-gui#14]

**Comment by kba** [comment]
In the prototype there was a handy on-line editor that allowed editing XML and XSLT directly in the browser using a syntax-highlighting textarea. While it is perpendicular to the idea that files should be unchangeable it allows quick changes (fixing typos and such) without jumping through the fix-locally-reupload-adapt-config-loop.

In this version, this feature hasn't been implemented yet though.

**Comment by kba** [comment]
Should we implement this or just hide the edit button for non-MINT files?
