### ISSUE TITLE
File Manager shows truncated file list 

### ISSUE THREAD

**Issue by d0rg0ld** [DM2E/dm2e-gui#17]
I uploaded a (ZIP_XML) file to OmNom. When switching to the File Manager, I can not always see the file in the list. Upon refresh, http://omnom.hu-berlin.de/#file-list/http://omnom.hu-berlin.de:/api/file shows different list items (sometimes none, sometimes 3, sometimes 10, sometimes 15)

**Comment by kba** [comment]
There's an error in the Javascript, which leads to truncation of the file list depending on the order of the files returned by the web service (which is essentially random). Will investigate.
