### ISSUE TITLE
Can not sort File Manager list

### ISSUE THREAD

**Issue by d0rg0ld** [DM2E/dm2e-gui#18]
This would be extremely important

**Comment by kba** [comment]
Should work again when #17 is fixed.

**Comment by d0rg0ld** [comment]
Well, how do I sort the File Manager List according to the various columns? There are no GUI elements supporting this ...

**Comment by d0rg0ld** [comment]
Sorting now works in workflow and config list, but NOT in file list!!!

**Comment by kba** [comment]
Yep there's a bug in sorttable I just fixed, redeploying in a minute, related to #16
