### ISSUE TITLE
Workflow parameter not deletable

### ISSUE THREAD

**Issue by kaiec** [DM2E/dm2e-gui#2]
When I edit a workflow, I can not delete workflow parameters anymore. Deletion only works when I create a new workflow parameter and then delete it immediately, before reopening the workflow again.

The same holds for connections that are created automatically. You can delete them when they are just created, but not later.

**Comment by kba** [comment]
There's a bug in the view logic there, have to investigate. Workaround for now: 
- Reload the page when you're at the workflow
- Delete parameter
- Save

**Comment by kba** [comment]
Apparenly, clicking the remove button works (the model is deleted from the collection), hence clicking the remove button two times will result in a variable-not-defined error. However these changes don't reach the workflow which doesn't register the "remove" event to the collection. So either the collections for inputParam/outputParam are not properly attached to the workflow or we're relying on information that changes between navigation (i.e. relying on a certain cid)

**Comment by kba** [comment]
I cannot reproduce this anymore. Possible this was fixed when I cleaned up the connector code.

**Comment by kba** [comment]
Yup, that was https://github.com/DM2E/dm2e-gui/commit/651aba7ce5e2c0dc11694bca51481f21e42f5002
