### ISSUE TITLE
Not sure about ZIP_XML

### ISSUE THREAD

**Issue by d0rg0ld** [DM2E/dm2e-gui#21]
The file upload option ZIP_XML suggests that one can upload an archive with many legacy xml files to be converted. Is this correct? Does it work already?

**Comment by kba** [comment]
Yes, that is the purpose of ZIP_XML. Is not yet implemented though (XsltService.java would be the place but not sure how to make this as efficient as possible).

**Comment by kba** [comment]
The Zip-Iterator input file handles this case now. https://github.com/DM2E/dm2e-gui/commit/4f65fef1e4a8238aae5616d2cd051a6f61c0a255
