### ISSUE TITLE
Create Config: Long list of mapping/source files very inconvenient

### ISSUE THREAD

**Issue by d0rg0ld** [DM2E/dm2e-gui#25]
There is no visual feedback when someone drags an ID from the list to its respective field. Only when the mouse is over the field, you get visual feedback, before its a blind run.

The list is _way_ to long, one must be able to filter the list and to _scroll_ through it !!!

**Comment by kba** [comment]
Indeed, this is the bare bones solution, it must be refined and prettied up. I'll post updates in #24 as I will do that.
