### ISSUE TITLE
Create Workflow: InputParams set as "required=true" shown as "required=false" after switching to "create config" without saving workflow

### ISSUE THREAD

**Issue by d0rg0ld** [DM2E/dm2e-gui#27]
Workflow configured with "required" Parameters - then button "Create Config" without saving - Required Parameters not shown in Create Config Param List - jump back to "edit workflow" - all params set to "required = false"

**Comment by kba** [comment]
Sounds like a bug, probably the required state is not saved at all, have to investigate.
