### ISSUE TITLE
Published Output: Where is the Link to the RDF Representation / Pubby page ?

### ISSUE THREAD

**Issue by d0rg0ld** [DM2E/dm2e-gui#28]
Is the URI of the created dataset hidden somewhere in the Log File? What about a pubby Page for this content?

**Comment by kba** [comment]
It is hidden in the log file right now. They appear in the file list though, switch to the File Manager and sort ascending by "Upload Date". The generated files are named 'generated_TIMESTAMP.xml'. We will link to the page in pubby page when @kaiec has connected the Omnom Triplestore with pubby  (see https://github.com/DM2E/pubby).

From a provider's perspective: What would you want to see in the progress page? Where should the link be put when the page is ready?

**Comment by d0rg0ld** [comment]
> From a provider's perspective: What would you want to see in the progress page? Where should the link be put when the page is ready?

If the job has finished successfully, it would be great to get to a page that shows an overview on what has been ingested in that job. for example, if multiple records have been ingested, some kind of simple statistics such as number of records, different types of records etc. would be great. This page could also feature a link to a "top level" Pubby representation of the respective provider, showing a list of the existing datasets created to date. this list could serve as an entry point for examining the different datasets, i.e. from this list, all the ingested records should be reachable by "following one's nose" ...

**Comment by kba** [comment]
Omnom now provides the link to Pubby, there isn't much more we can do in DM2E/dm2e-gui without reinventing the wheel of Pubby. So, I'll close this here and refer to https://github.com/DM2E/pubby/issues/1.
