### ISSUE TITLE
Expose start time of jobs

### ISSUE THREAD

**Issue by kba** [DM2E/dm2e-gui#30]
in the list of jobs. blocked by https://github.com/DM2E/dm2e-ws/issues/2

**Comment by d0rg0ld** [comment]
It would also be good to show the "owner" of the job ...

**Comment by kba** [comment]
> It would also be good to show the "owner" of the job ...
> Yes it would, but unfortunately that isn't straightforward  (See https://github.com/DM2E/dm2e-ws/issues/2 and https://github.com/DM2E/dm2e-ws/issues/3). In essence: Jobs are created by web services are created by workflow jobs are created by workflows are created by users. This isn't easy to traverse and requires a bit of tinkering with the model.
