### ISSUE TITLE
Filter all files/workflows/configs/jobs, showing only those created by the currently logged-in user

### ISSUE THREAD

**Issue by d0rg0ld** [DM2E/dm2e-gui#33]
On a first thought it should be straightforward to implement a global filter for all files/workflows/configs/jobs limiting their display to the ones created by the currently logged-in user only. of course, group based permissions would be cool, but such a simple feature could also be of great help -> Provide a "global filter by username" option somewhere in the menu?

**Comment by kba** [comment]
I've been implementing this but I'd prefer a generic solution because that will make it easier to do other filters (like 'show only XML files' or 'less than a day old' or 'generated files only' or 'workflow jobs only'. I'll be tracking progress in #29.
