### ISSUE TITLE
"Self explaining" job names.

### ISSUE THREAD

**Issue by d0rg0ld** [DM2E/dm2e-gui#42]
For me its almost a bug. If I "Run" a config, I am directed to the Job page where the Job has some hex-string as name. Would it be possible to auto-create some label for it based on the involved workflow, config and timestamp?

**Comment by kba** [comment]
Requires changes to WorkflowJobPojo but will be done, see https://github.com/DM2E/dm2e-ws/issues/8

**Comment by kba** [comment]
Fixed by https://github.com/DM2E/dm2e-ws/commit/d1badbdc3b651ef29e4712bdd0cc4fcb106f675e
