### ISSUE TITLE
Some download links point to localhost:9998

### ISSUE THREAD

**Issue by kthth** [DM2E/dm2e-gui#46]
Files with "last updated" state "Just now" have a link pointing to localhost:9998 on the Download button on the left

![omnom-localhost](https://f.cloud.github.com/assets/5594445/1483715/07ab2924-46fc-11e3-95d0-e8aa1802c056.png)

**Comment by kba** [comment]
Yes, those are old workflows created for testing. Workflows created with the GUI have the correct URI and behave correctly.
