### ISSUE TITLE
Workflows and WF Configs need a label so that I can give them names during creation. 

### ISSUE THREAD

**Issue by kaiec** [DM2E/dm2e-gui#5]
Workflows and WF Configs need a label so that I can give them names during creation.

**Comment by kba** [comment]
They do have labels, as do all Pojos extending SerializablePojo. Now to see where this can be exposed in the UI

**Comment by kba** [comment]
Workflows and configs can be named, there is a text input field near the top now that can be changed and is persisted whenever the workflow/config is saved.
