### ISSUE TITLE
File delete / Behaviour in File Manager

### ISSUE THREAD

**Issue by d0rg0ld** [DM2E/dm2e-gui#50]
How is the delete functiojn supposed to work (As it is greyed out: Is it supposed to be used at all)?

Nevertheless it seems to do something: I cklicked on it (intended) and then I suddenly could see all the files of all OmNom users - So the "my stuff" filter was suddenly deactivated here.

After ticking "my stuff" off and back on the filter worked again. Now I can see the deleted file in the list with status "deleted"

**Comment by kba** [comment]
Apart from the filter glitch (will investigate), this is how it should work. When files are deleted their metadata is preserved but the status is set to DELETED. The intention is that we don't want to break provenance by making file data requests result in 404 but 410 and metadata requests return 200 and the data.

The UI should probably just filter deleted files.
