### ISSUE TITLE
The collection and provider ids are not stored or only not shown on Pubby

### ISSUE THREAD

**Issue by edroege** [DM2E/dm2e-gui#66]

**Comment by kba** [comment]
Please give an example, i.e. copy the URL of the Configuration where this happens for you, so we can debug it.

**Comment by edroege** [comment]
For example: This is the Pubby output: http://lelystad.informatik.uni-mannheim.de:3000/data/html/ingested/dataset/uber/123/1385641750183

Job: Job 'Service for WF: Dingler Workflow'
Workflow: Dingler Workflow
Configuration: http://omnom.hu-berlin.de/#/config-edit/http://omnom.hu-berlin.de/api/config/a34defe4-523a-4428-bebd-8dfb5d6e02df

**Comment by kba** [comment]
The Ingestion URL is correct, so the publish component works. The URLs of the Aggregations are created by the XSLT-ZIP component, which expects a few parameters to create the URLs (also named provider-id and dataset-id). I added the missing connectors.

Now the configuration runs through fine with the correct URLs: http://omnom.hu-berlin.de/#job/http://omnom.hu-berlin.de/api/job/3343acb8-c1f8-44ba-ae24-c20116d0d16a, resulting in http://lelystad.informatik.uni-mannheim.de:3000/data/html/ingested/dataset/uber/123/1385714691083.

This must be documented of course, it's not completely clear. In particular we need to expose web service documentation to the users.
