### ISSUE TITLE
Edit fields have strange behaviour, only overwrite possible

### ISSUE THREAD

**Issue by kaiec** [DM2E/dm2e-gui#7]
When I edit a workflow config and want to change the value of a form field, I can not edit it. When I start typing, the old value disappears. This is unfamiliar to me and not comfortable if I just want to change something.

EDIT: This does not happen any time, now I have editable fields, just after I run the job (and still are on the config edit view, as job view does not come up, see other bug: #8 )

**Comment by kba** [comment]
The intention here is that default values should be displayed as "placeholder" and actual parameter Values should be editable. Might be that making everything editable is the more intuitive solution.
