### ISSUE TITLE
Start job does not open job view

### ISSUE THREAD

**Issue by kaiec** [DM2E/dm2e-gui#8]
I reused an older config, changed something and then pressed start, but now the job view does not come up. 

Only workaround I have to get to the job data is to be very quick and copy the job URI when it is shown in the messages, then retrieve the RDF description with  the Infos.

**Comment by kba** [comment]
Probably the same problem as in #2

**Comment by kba** [comment]
Actually, this works for me. Fixed by acbe7b63ea2ec3d1a3fcb40cf3f1d8f360ae5562 ?
