### ISSUE TITLE
XSLT Zip Transformation only uses parameter default values for provider-id and dataset-id.

### ISSUE THREAD

**Issue by kaiec** [DM2E/dm2e-gui#9]
Currently, the output of Kilians XSLT contains DATAPROVIDER_ABB_NOT_SET and REPOSITORY_ABB_NOT_SET instead of the values of provider-id and dataset-id. Both values are the default values set in the service code but should be overwritten by the parameter values set in OmNom.

**Comment by kba** [comment]
Can't reproduce this.
